{{ if not .Values.ingress.useIngress}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: swag-frontend-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{ end }}